[project]
name = "chat-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymongo>=4.12.0",
    "requests>=2.32.3",
    "streamlit>=1.44.1",
    "streamlit-authenticator>=0.4.2",
    "streamlit-extras>=0.6.0",
]
